name: Build ruleset and geodata
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "update_version=$(date -d '+8 hours' +%Y-%m-%d)" >> ${GITHUB_ENV}
          echo "sougouinput=https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt" >> ${GITHUB_ENV}
          echo "ai_non_ip=https://ruleset.skk.moe/Clash/non_ip/ai.txt" >> ${GITHUB_ENV}
          echo "gemini_non_ip=https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.list" >> ${GITHUB_ENV}
          echo "apple_cdn=https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt" >> ${GITHUB_ENV}
          echo "apple_cn_non_ip=https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt" >> ${GITHUB_ENV}
          echo "microsoft_cdn_non_ip=https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt" >> ${GITHUB_ENV}
          echo "domestic_non_ip=https://ruleset.skk.moe/Clash/non_ip/domestic.txt" >> ${GITHUB_ENV}
          echo "direct_non_ip=https://ruleset.skk.moe/Clash/non_ip/direct.txt" >> ${GITHUB_ENV}

          echo "domestic_ip=https://ruleset.skk.moe/Clash/ip/domestic.txt" >> ${GITHUB_ENV}
          echo "china_ip=https://ruleset.skk.moe/Clash/ip/china_ip.txt" >> ${GITHUB_ENV}
          echo "china_ip_ipv6=https://ruleset.skk.moe/Clash/ip/china_ip_ipv6.txt" >> ${GITHUB_ENV}

        shell: bash
      
      - name: Clone Repository
        uses: actions/checkout@master

      - name: Checkout DustinWin/domain-list-custom
        uses: actions/checkout@v4
        with:
          repository: DustinWin/domain-list-custom
          path: custom

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: ruleset

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./custom/go.mod
          cache-dependency-path: ./custom/go.sum

      - name: Generate geodata
        run: |
          mkdir -p ./ruleset/mydata

          curl -sSL "${sougouinput}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/sougouinput"
          curl -sSL "${ai_non_ip}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/ai"
          curl -sSL "${gemini_non_ip}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/gemini"
          curl -sSL "${apple_cdn}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/apple@cdn"
          curl -sSL "${apple_cn_non_ip}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/apple@cn"
          curl -sSL "${microsoft_cdn_non_ip}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/microsoft@cdn"
          curl -sSL "${domestic_non_ip}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/domestic"
          curl -sSL "${direct_non_ip}" | grep -E 'DOMAIN,|DOMAIN-SUFFIX,|DOMAIN-KEYWORD' | sed -e 's/^DOMAIN,/full:/' -e 's/^DOMAIN-SUFFIX,//' -e 's/^DOMAIN-KEYWORD,/keyword:/' > "./ruleset/mydata/direct@skk"

          cd ./ruleset/
          go run ./ --datapath=./mydata/ --outputname skk.dat

      - name: Release and upload geodata
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: geodata
          tag: ${{ github.ref }}
          overwrite: false
          body: |
            geodata 文件更新于 ${{ env.update_version }}
          file_glob: false
          file: ./ruleset/skk.dat

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
